version: "3"
networks:
  selenoid:
    external:
      name: selenoid

services:
  selenoid:
    networks:
      selenoid: null
    image: aerokube/selenoid:latest-release
    volumes:
      - ${PWD}/selenoid/config:/etc/selenoid
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/selenoid/video:/opt/selenoid/video
      - ${PWD}/selenoid/logs:/opt/selenoid/logs
    command:
      [
        "-conf",
        "/etc/selenoid/browsers.json",
        "-video-output-dir",
        "/opt/selenoid/video",
        "-log-output-dir",
        "/opt/selenoid/logs",
        "-container-network",
        "selenoid",
      ]
    container_name: selenoid
    ports:
      - "4444:4444"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=${PWD}/selenoid/video

  selenoid-ui:
    networks:
      selenoid: null
    image: aerokube/selenoid-ui:latest-release
    container_name: selenoid-ui
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
