version: 2.1

aliases:
  - &defaults
    working_directory: ~/repo
    docker:
      - image: circleci/ruby:2-node-browsers

  - &nodejs
    working_directory: ~/repo/nodejs-wdio
    docker:
      - image: circleci/ruby:2-node-browsers
  
  - &ruby
    working_directory: ~/repo/ruby-capybara
    docker:
      - image: circleci/ruby:2-node-browsers

jobs:
  prepare:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Download Selenium
          command: "curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar"
      - run: mkdir -p ./selenium-logs/
      - secrethub/install:
          version: 0.40.0
      - run: secrethub read griou/livestorm/users > fixtures/users.fixture.json
      - run: secrethub read griou/livestorm/browserstack > config/browserstack.config.yml
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  bundle-install:
    <<: *ruby
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gem-cache-v1-{{ arch }}-{{ .Branch }}
            - gem-cache-v1
      - run: bundle install
      - run: npm install -D allure-commandline
      - save_cache:
          key: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/repo/ruby-capybara
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  bundle-test:
    <<: *ruby
    steps:
      - attach_workspace:
          at: ~/repo
      - run: pwd
      - run: gem list
      - run: rake e2e:ci_chrome
      - run: rake e2e:ci_browserstack
      - store_artifacts:
          path: ./allure-report/

  npm-install:
    <<: *nodejs
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: |
            npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  npm-test:
    <<: *nodejs
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Start Selenium
          command: java -jar ../selenium-server-standalone-3.5.3.jar -log ../selenium-logs/selenium-node.log
          background: true
          when: always
      - run:
          name: run desktop test
          command: npm run ci:desktop
          when: always
      - run:
          name: run mobile test
          command: npm run ci:mobile
          when: always
      - run:
          name: Make history dir for allure
          command: mkdir allure-results/history
          when: always

      - run:
          name: Get previous artifact links
          command: curl -G --data-urlencode "branch=$CIRCLE_BRANCH" "https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/latest/artifacts?circle-token=$CIRCLE_TOKEN&filter=completed" | grep -o 'https\:\/\/.*history\/history.*\.json' > artifacts.txt || true
          when: always

      - run:
          name: Download history artfacts
          command: <artifacts.txt xargs -P4 -I % wget %?circle-token=$CIRCLE_TOKEN
          when: always
      - run:
          name: Rename and copy history artifacts to allure-result
          command: |
            mv history.json?circle-token=$CIRCLE_TOKEN history.json && mv history-trend.json?circle-token=$CIRCLE_TOKEN history-trend.json || true
            cp history.json allure-results/history/ && cp history-trend.json allure-results/history/ || true
            mv categories-trend.json?circle-token=$CIRCLE_TOKEN categories-trend.json && mv duration-trend.json?circle-token=$CIRCLE_TOKEN duration-trend.json || true
            cp categories-trend.json allure-results/history/ && cp duration-trend.json allure-results/history/ || true
            mv retry-trend.json?circle-token=$CIRCLE_TOKEN retry-trend.json || true
            cp retry-trend.json allure-results/history/ || true
          when: always
      - run:
          name: generate allure report
          command: npm run report:make
          when: always
      - store_test_results:
          path: ./junit-report/
      - store_artifacts:
          path: ./junit-report/
      - store_artifacts:
          path: ./allure-report/
      - store_artifacts:
          path: ./selenium-logs/
  
orbs:
  secrethub: secrethub/cli@1.0.1

workflows:
  version: 2
  e2e:
    jobs:
      - prepare
      - npm-install:
          requires:
            - prepare
      - bundle-install:
          requires:
            - prepare
      - bundle-test:
          requires:
            - bundle-install
      - npm-test:
          requires:
            - bundle-test
