source "https://rubygems.org"

ruby '2.7.1'

group :development, :test do
  gem 'capybara'
  gem 'rake'
  gem 'parallel'
  gem 'parallel_tests'
  gem 'selenium-webdriver'
  gem 'rspec'
  gem 'rspec_junit_formatter'
  gem 'allure-rspec'
  gem 'browserstack-local'
  gem 'rubocop'
  gem 'reek'
end
